adminUser:
  password: vault:jx-aps-skullribbon/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-skullribbon:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-skullribbon:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-skullribbon/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-skullribbon/prow:hmacToken
